
import { VirtualFile } from '../types';
import { createFolder, createFile } from './virtualFileSystem';

// --- ANDROID ---
export const generateAndroidTemplate = (files: VirtualFile[]): VirtualFile[] => {
  let newFiles = [...files];
  newFiles = createFolder(newFiles, 'root', 'app');
  newFiles = createFolder(newFiles, 'app', 'src');
  newFiles = createFolder(newFiles, 'src', 'main');
  newFiles = createFolder(newFiles, 'main', 'java');
  newFiles = createFolder(newFiles, 'java', 'com');
  newFiles = createFolder(newFiles, 'com', 'example');
  newFiles = createFolder(newFiles, 'example', 'omega');
  
  const manifest = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.omega">
    <application
        android:label="Omega App"
        android:theme="@style/Theme.Omega">
        <activity android:name=".MainActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>`;
  newFiles = createFile(newFiles, 'main', 'AndroidManifest.xml', manifest);

  const mainActivity = `package com.example.omega

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.material3.Text

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            Text(text = "Generated by OMEGA OS")
        }
    }
}`;
  newFiles = createFile(newFiles, 'omega', 'MainActivity.kt', mainActivity);
  newFiles = createFile(newFiles, 'app', 'build.gradle', `plugins { id 'com.android.application' }\nandroid { namespace 'com.example.omega' }`);
  
  return newFiles;
};

// --- WEB (Modified for Instant Iframe Preview) ---
export const generateWebTemplate = (files: VirtualFile[]): VirtualFile[] => {
  let newFiles = [...files];
  newFiles = createFolder(newFiles, 'root', 'src');
  
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Omega Web App</title>
    <style>
        body { margin: 0; font-family: 'Segoe UI', sans-serif; background: #111; color: white; display: flex; align-items: center; justify-center: center; height: 100vh; }
        .container { text-align: center; }
        h1 { background: linear-gradient(to right, #00d2ff, #3a7bd5); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-size: 3rem; margin-bottom: 1rem; }
        button { padding: 10px 20px; background: #3a7bd5; border: none; color: white; border-radius: 5px; cursor: pointer; font-size: 1rem; }
        button:hover { background: #00d2ff; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Omega Web Live</h1>
        <p>This is a live preview of your code.</p>
        <button onclick="alert('System Operational')">Click Me</button>
    </div>
</body>
</html>`;

  newFiles = createFile(newFiles, 'root', 'index.html', htmlContent);
  newFiles = createFile(newFiles, 'src', 'main.js', `console.log("Omega Web System Initialized");`);
  return newFiles;
};

// --- GAME (Canvas) ---
export const generateGameTemplate = (files: VirtualFile[]): VirtualFile[] => {
  let newFiles = [...files];
  newFiles = createFolder(newFiles, 'root', 'assets');
  newFiles = createFolder(newFiles, 'root', 'scripts');
  
  const gameHtml = `<!DOCTYPE html>
<html>
<head>
    <style>body { margin: 0; overflow: hidden; background: #000; display: flex; justify-content: center; align-items: center; height: 100vh; }</style>
</head>
<body>
    <canvas id="gameCanvas" width="800" height="600" style="border:1px solid #333; box-shadow: 0 0 20px rgba(0,255,255,0.2);"></canvas>
    <script>
        const canvas = document.getElementById('gameCanvas');
        const ctx = canvas.getContext('2d');
        let player = { x: 400, y: 300, size: 20, color: '#00d2ff' };
        
        function update() {
            // Simple movement
            player.x += (Math.random() - 0.5) * 2;
            player.y += (Math.random() - 0.5) * 2;
            draw();
            requestAnimationFrame(update);
        }
        
        function draw() {
            ctx.fillStyle = 'rgba(0,0,0,0.1)';
            ctx.fillRect(0, 0, canvas.width, canvas.height);
            ctx.fillStyle = player.color;
            ctx.fillRect(player.x, player.y, player.size, player.size);
        }
        update();
    </script>
</body>
</html>`;

  newFiles = createFile(newFiles, 'root', 'index.html', gameHtml);
  return newFiles;
};

// --- BACKEND ---
export const generateBackendTemplate = (files: VirtualFile[]): VirtualFile[] => {
  let newFiles = [...files];
  newFiles = createFolder(newFiles, 'root', 'src');
  newFiles = createFolder(newFiles, 'src', 'controllers');
  newFiles = createFolder(newFiles, 'src', 'models');
  
  const serverJs = `
const express = require('express');
const app = express();
const port = 3000;

app.get('/', (req, res) => {
  res.json({ status: 'online', system: 'OMEGA' });
});

app.listen(port, () => {
  console.log(\`Server running on port \${port}\`);
});
`;
  newFiles = createFile(newFiles, 'src', 'server.js', serverJs);
  newFiles = createFile(newFiles, 'root', 'package.json', `{\n  "name": "omega-api",\n  "dependencies": {\n    "express": "^4.18.2"\n  }\n}`);
  return newFiles;
};

// --- AI AGENT ---
export const generateAgentTemplate = (files: VirtualFile[]): VirtualFile[] => {
  let newFiles = [...files];
  newFiles = createFolder(newFiles, 'root', 'brain');
  
  const agentCore = `
import { GoogleGenAI } from '@google/genai';

export class VoiceAgent {
    constructor(apiKey) {
        this.client = new GoogleGenAI({ apiKey });
    }

    async listen(audioBuffer) {
        console.log("Processing audio stream...");
        return "I heard you.";
    }

    async speak(text) {
        console.log("TTS Output:", text);
    }
}
`;
  newFiles = createFile(newFiles, 'brain', 'core.js', agentCore);
  newFiles = createFile(newFiles, 'root', 'config.json', `{\n  "voice": "JARVIS",\n  "wakeWord": "OMEGA"\n}`);
  return newFiles;
};
