
import { ModelId } from './types';

export const APP_NAME = "AI Agent Studio";
export const APP_VERSION = "2.0.0 (Autonomous)";

export const MODEL_OPTIONS = [
  { id: ModelId.GEMINI_FLASH, name: "Gemini 2.5 Flash (Speed)", description: "Best for fast coding & agents" },
  { id: ModelId.GEMINI_PRO, name: "Gemini 3.0 Pro (Architect)", description: "Best for planning & complex logic" },
];

export const AGENT_PERSONAS = {
  ARCHITECT: "You are a Senior System Architect. Your goal is to design the file structure and technical specifications for the requested application. Output strictly structured JSON.",
  DEVELOPER: "You are an Expert Android/Web Developer. Write clean, production-ready code. Do not wrap in markdown if asked for raw content.",
  DEBUGGER: "You are a QA Engineer. Analyze the code for errors and suggest fixes.",
};

export const INITIAL_FILES = [
  { id: 'root', name: 'Project', type: 'folder', parentId: null },
  { id: 'src', name: 'src', type: 'folder', parentId: 'root' },
  { id: 'main', name: 'main.kt', type: 'file', parentId: 'src', language: 'kotlin', content: '// Entry point\nfun main() {\n    println("Hello from Autonomous AI Studio")\n}' },
  { id: 'readme', name: 'README.md', type: 'file', parentId: 'root', language: 'markdown', content: '# New Project\nGenerated by AI Agent Studio' },
];
